Imagenet benchmarking
clane9/columnformers pull request #1
Opened 2023-12-27 00:42 UTC by IhabBendidi

Added two main parts : 

- Handling of the training and test of both ImageNet100 and a subset of Imagenet100 for debugging purposes

- Made an initial baseline for the results of training an initial columnformer architecture on imagenet100

2023-12-27 20:10 UTC, clane9 requested changes
Hi @IhabBendidi, thank you for the PR, this is great! I made some change requests, mostly organizational. But then will be glad to merge.

2023-12-27 20:10 UTC, clane9 commented on Column_Former_ImageNet100_Benchmark.py
Let's not include this file for now and just have the notebook. Less to maintain.

2023-12-27 20:10 UTC, clane9 commented on Column_Former_ImageNet100_Benchmark.ipynb
Can we move this to `notebooks/imagenet-100_benchmark.ipynb`?

2023-12-27 20:10 UTC, clane9 commented on data/imagenet100/test_labels.txt
Let's not include the train/test label files in the repo. They can be generated easily enough on the fly.

2023-12-27 20:10 UTC, clane9 commented on README.md
> +- [x] Implement image classification train/eval pipelines ([`benchmark.ipynb`](columnformers/Column_Former_ImageNet100_Benchmark.ipynb)) or ([colab](https://colab.research.google.com/drive/1fImu9rEFd
To avoid needing to maintain two notebooks, one in github one in colab, you could replace the dedicated colab link with a colab-from-github link like:

https://colab.research.google.com/github/IhabBendidi/columnformers/blob/imagenet_benchmarking/Column_Former_ImageNet100_Benchmark.ipynb

2023-12-27 20:10 UTC, clane9 commented on README.md
> +- [x] Get baseline performance (done[here](benchmark_imagenet100))
Link typo

2023-12-27 20:10 UTC, clane9 commented on benchmark_imagenet100.md
> +
This is great. Can we rename this file to `RESULTS.md`?

A few suggested changes:

```suggestion
# Results

## ImageNet-100

Columnformer performance trained on [ImageNet-100](https://huggingface.co/datasets/clane9/imagenet-100) at 128x128 resolution for 100 epochs.

| description | commit | # of params | geometry | accuracy |
|------------|--------|-------------|-----------|----------|
| baseline | [690dd2c](https://github.com/IhabBendidi/columnformers/tree/690dd2c733f1fa029e43e87cf5ce99a5c3b90608)| 47M |  [8, 12, 16]  |      22.8%       |

```

2023-12-28 13:28 UTC, IhabBendidi commented
hi @clane9, thanks for observations on the changes, its more organized this way ! I have done the requested modifications. Let me know if something else is needed

2023-12-28 15:06 UTC, clane9 approved these changes
LGTM!

2023-12-28 15:07 UTC, merged